### ISSUE TITLE
Consider to add support for Functions?

### ISSUE THREAD

**Issue by leesiongchan** [locize/fluent_conv#1]
https://projectfluent.org/fluent/guide/functions.html

**Comment by jamuhl** [comment]
why are functions not supported? "only" thing this lib does is taking a fluent text file and convert that to JSON

**Comment by leesiongchan** [comment]
Somehow the placeable syntax will go missing if we use functions. I have made a very simple demo on below.

https://codesandbox.io/s/n5yp8q9lyp

**Comment by jamuhl** [comment]
you're right...seems we need to add that to the serializer.

**Comment by jamuhl** [comment]
@leesiongchan took a little longer...should now be supported in fluent_conv@1.1.0

**Comment by leesiongchan** [comment]
Thank you very much @jamuhl
