### ISSUE TITLE
GroupComments type

### ISSUE THREAD

**Issue by ElForastero** [locize/fluent_conv#3]
Hi 👋 

Can we supress these messages about unknown type on comments' statements? They are annoying and polute the console output.

I can make a PR, but I'm not sure if this is the right way to deal with the issue.

![image](https://user-images.githubusercontent.com/5102818/106745543-abb78700-663a-11eb-8a40-3ab2bc7b646a.png)

My case:
I have a script that watches for changes in *.ftl locales and converts them into *.json files. And the console is really dirty :)

**Comment by jamuhl** [comment]
Not sure what group comments are?!? But the log comes from here: https://github.com/locize/fluent_conv/blob/master/lib/ftl2jsSerializer.js#L8

Guess there is no meaningful conversion to JSON for it...so you just might add a serializing function for it returning nothing?

PR welcome

**Comment by ElForastero** [comment]
> Not sure what group comments are?!?

Oh, I get it... These are double- and triple-hash comments. :)

From the projectfluent docs:
![image](https://user-images.githubusercontent.com/5102818/106769869-de6f7880-6656-11eb-8d3f-2ae17e9a8116.png)

**Comment by ElForastero** [comment]
Here we go

https://github.com/locize/fluent_conv/pull/4
